services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - ./Data:/app/Data

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "3000:80"
