version: "3.8"
services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hab-backend
    env_file:
      - .env                
    ports:
      - "5000:5000"
    volumes:
      - ./Data:/app/Data    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hab-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend