services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    runtime: python-3.10
    plan: free
    region: oregon
    rootDir: backend
